### ISSUE TITLE
Edu-sharing assests sometimes are displayed too big

### ISSUE THREAD

**Issue by kulla** [serlo/serlo-editor-for-edusharing#288]
Issue: "Die Größe von eingefügten Bildern oder Videos aus edu-sharing kann nicht verändert werden." -> Solution: Find a way to set max-height for the integration

Notes:

* allein stehendes Bild, nicht Serlo-Multimedia-Inhalt

**Comment by LarsTheGlidingSquirrel** [comment]
Done & published in release 1.2.0
