### ISSUE TITLE
Remove `exerciseVisibleInSuggestion` from Editor config

### ISSUE THREAD

**Issue by hejtful** [serlo/serlo-editor-for-edusharing#376]
Once [the Editor PR](https://github.com/serlo/frontend/pull/3907) has been merged and the new Editor version published, remove the deprecated `exerciseVisibleInSuggestion` prop from Editor's `pluginsConfig`.

**Comment by hugotiburtino** [comment]
Is it still relevant?

**Comment by hugotiburtino** [comment]
It doesn't seem so. So I'll close it, in order to archive the bucket without any remaining issues.
